# -*- coding: utf-8 -*-
"""forecasting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FoTviA4DzB5i6sZ8fuMkcXx_LbVhimU4
"""

from statsmodels.tsa.statespace.sarimax import SARIMAX


def train_sarima(train_data):

    model = SARIMAX(
        train_data,
        order=(1, 1, 1),
        seasonal_order=(1, 1, 1, 12),
        enforce_stationarity=False,
        enforce_invertibility=False
    )

    model_fit = model.fit(disp=False)

    return model_fit


def forecast_sales(model_fit, steps):

    forecast = model_fit.forecast(
        steps=steps
    )

    return forecast