# -*- coding: utf-8 -*-
"""preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12uZ4_SsmDXNyqr0nreAYzPVXz52daIjY
"""

import pandas as pd


def load_data(file_path):
    df = pd.read_csv(file_path, encoding="latin1")
    return df


def preprocess_data(df):
    df["Order Date"] = pd.to_datetime(
        df["Order Date"],
        format="mixed",
        errors="coerce"
    )

    df = df.dropna(subset=["Order Date"]).copy()

    df["Sales"] = pd.to_numeric(
        df["Sales"],
        errors="coerce"
    )

    monthly_sales = (
        df.groupby(
            pd.Grouper(key="Order Date", freq="ME")
        )["Sales"]
        .sum()
    )

    return monthly_sales